dlang/dconf.org

2015/macros.ddoc
=> Add UVU to sponsors

2015/Makefile, 2015/registration.dd, 2015/thankyou.dd
I'm having problems with the Amazon payment button, so I'll deal with that in a later PR.
=> add payment methods and thankyou pages

2015/index.dd
from http://dconf.org/2015/registration.html
=> note early bird deadline on home page

2015/registration.dd
Preregistration ticket prices is over, set regular prices.
=> Pregistration over

2015/talks/strasuns.dd
=> Minor tweaks to Mihails Strasuns talk description

2015/talks/gubler.dd
Shone is the right verb here, while I presume he's applying for his master's since he's almost done with his bachelor's.
=> fix grammatical error and degree name

2015/talks/smith.dd
Trimmed it down to main points.
=> Andy S talk description less verbose.

2015/talks/gubler.dd, 2015/talks/neves.dd
@andralex  pls consider for merge.
Cheers,
A.
=> Last two talks added. Gubler + Neves.

2016/registration.dd, 2016/thankyou.dd
Copied from 2015 registration page, and updated. It isn't linked to yet from the home page - will do so after this is working.
=> add registration page

2016/Makefile, 2016/macros.ddoc, 2016/venue.dd
Confirmed location. Also adding one recommended hotel (locals please add more).
=> Add venue information

2016/Makefile, 2016/index.dd, 2016/macros.ddoc, 2016/registration.dd
=> Early Bird Registration

.gitignore, 2016/talks/cehreli.dd
Apologies for pushing .gitignore to the same branch. :-/
=> Cehreli abstract update

2016/talks/colvin.dd
@andralex  @WalterBright Website has two talks at 130PM. Does this fix?
=> John colvin speaking time.

2016/talks/schadek.dd
=> Schadek Slides URL

2016/Makefile, 2016/talks/alexandrescu.dd, 2016/talks/bright.dd, 2016/talks/lucarella.dd, 2016/talks/marques.dd, 2016/talks/sechet.dd, 2016/talks/smith.dd
=> Talk slides

2016/talks/hunsur.dd
=> Add slides to Skiron talk

2016/talks/alexandrescu.dd, 2016/talks/bright.dd, 2016/talks/cehreli.dd, 2016/talks/clugston.dd, 2016/talks/colvin.dd, 2016/talks/hunsur.dd, 2016/talks/lucarella.dd, 2016/talks/marques.dd, 2016/talks/nacke.dd, 2016/talks/nowak.dd, 2016/talks/panel1.dd, 2016/talks/panel2.dd, 2016/talks/panel3.dd, 2016/talks/panteleev.dd, 2016/talks/schadek.dd, 2016/talks/schveighoffer.dd, 2016/talks/sechet.dd, 2016/talks/smith.dd, 2016/talks/thaut.dd, 2016/talks/watson.dd, 2016/talks/zvibel.dd
Not 100% sure that this is how it works, but from reading the macros, I think this is it.
=> Add video links

2017/registration.dd
Early Bird registration is over.
=> Regular Admission is 400.00

2017/index.dd
Sorry that I am late to the party.
I will hopefully be able to extend this text soon.
=> Add notice for the DConf hackathon

2017/includes/style.css, 2017/macros.ddoc
The DConf page is deeply in need of some love. This is a first step on a long road.
Header
----------
Before:
After:
Footer
---------
Before:
After:
CC @andralex
=> Fix header + footer

2017/contact.dd, 2017/registration.dd
Btw `dconf@dlang.org` would be pretty sweat as well (and would avoid the risk of being outdated)
=> Registration: update email address

2017/schedule/index.dd
This pull request fixes a minor mistake in the schedule.
=> Fix Saturday May 7 to Sunday May 7.

2017/talks/buclaw.dd
@acehreli - I've had my head down for a while.
=> Add abstract and bio for self

2017/talks/macros.ddoc
Adding a handy link to https://docs.google.com/document/d/1L5edu6LLj3Afa3tPgqk-aX-fErwr7sPj37Dt5avoc5w/edit#
=> Add the idea document to the hackathon page

index.html
To be pulled right after announcement.
cc @mdparker @WalterBright @acehreli
=> Kick-off DConf 2018

2018/macros.ddoc
=> Update copyright year with $(YEAR)

2018/index.dd
Imho the video is really nice: https://vimeo.com/167235872
Preview:
=> Add summary trailer from DConf16

netlify.sh, netlify.toml
Allows previewing a PR via netlify.
=> Add PR preview via netlify

2018/Makefile
s.t. it's not forgotten to add the PDFS
e.g. https://github.com/dlang/dconf.org/pull/254
=> Use a wildcard for PDFs to automatically add all PDFs

2019/schedule/index.dd
The schedule is a little different this year.
=> [2019] Change times

2020/index.html
Please don't merge this before I've pulled the trigger on the blog post. I intend to merge it just before I publish the post.
=> Add keynote info

2023/index.html
The description of the event was not updated regarding the dates
=> fix: wrong dates in description of index.html

2023/index.html
=> Fix Murilo blog link
